---
jobs:
- name: job-publish
  public: true
  serial: true
  plan:
  - get: resource-tutorial
    trigger: true
  - put: hello-world-docker-image
    params:
      build: resource-tutorial/docker
- name: Image-Pull-and-Run
  public: true
  serial: true
  plan:
  - get: resource-tutorial
  - get: hello-world-docker-image
    passed: [job-publish]
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: dhaneshande/nodeappbuild}
        inputs:
        - name: job-publish
      run:
        path: /bin/bash
        args:
        - -exc
        - |
          pwd
          ls -R
          cd /usr/src/app
          ls -R
          npm install
          npm start      

resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/dhaneshande/nodeprebuildrun.git

- name: hello-world-docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-hello-world}}
