---
jobs:
- name: job-publish
  public: true
  serial: true
  plan:
  - get: resource-tutorial
    trigger: true
  - put: hello-world-docker-image
    params:
      build: resource-tutorial/docker

resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/dhaneshande/DockerbuildandPushWithVersioning.git

- name: hello-world-docker-image
  type: docker-image
  source:
    repository: {{docker-hub-image-hello-world}}
